# Generated by Django 6.0.4 on 2026-04-09 06:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='KategoriPengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('warna', models.CharField(choices=[('orange', 'Orange'), ('green', 'Hijau'), ('purple', 'Ungu'), ('blue', 'Biru'), ('red', 'Merah'), ('yellow', 'Kuning')], default='blue', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Kategori Pengeluaran',
            },
        ),
        migrations.CreateModel(
            name='PengaturanToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='Toko Sumber Rezeki', max_length=200)),
                ('alamat', models.TextField(blank=True)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('npwp', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('ppn_aktif', models.BooleanField(default=True)),
                ('ppn_persen', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('diskon_maksimal', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('pembulatan', models.CharField(choices=[('none', 'Tidak ada'), ('up', 'Ke atas'), ('down', 'Ke bawah')], default='none', max_length=20)),
                ('format_nomor_transaksi', models.CharField(default='TRX-YYYY-{seq}', max_length=50)),
                ('reset_nomor', models.CharField(choices=[('hari', 'Setiap hari'), ('bulan', 'Setiap bulan'), ('tahun', 'Setiap tahun'), ('tidak', 'Tidak reset')], default='bulan', max_length=10)),
                ('ukuran_kertas', models.CharField(choices=[('thermal58', 'Thermal 58mm'), ('thermal80', 'Thermal 80mm'), ('thermal88', 'Thermal 88mm'), ('a4', 'A4')], default='thermal58', max_length=20)),
                ('margin_printer', models.IntegerField(default=5)),
                ('cetak_otomatis', models.BooleanField(default=True)),
                ('catatan_struk', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Toko',
            },
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=300)),
                ('nominal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='pengeluaran/')),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.kategoripengeluaran')),
            ],
            options={
                'verbose_name_plural': 'Pengeluaran',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('satuan', models.CharField(choices=[('pcs', 'Pcs'), ('botol', 'Botol'), ('cup', 'Cup'), ('kg', 'Kg'), ('gram', 'Gram'), ('liter', 'Liter'), ('porsi', 'Porsi'), ('pack', 'Pack')], default='pcs', max_length=10)),
                ('harga_beli', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('harga_jual', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stok', models.IntegerField(default=0)),
                ('stok_minimum', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.kategori')),
            ],
            options={
                'verbose_name_plural': 'Produk',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('diskon_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diskon_nominal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('ppn_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ppn_nominal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('metode_bayar', models.CharField(choices=[('tunai', 'Tunai'), ('qris', 'QRIS'), ('debit', 'Debit')], default='tunai', max_length=10)),
                ('jumlah_bayar', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('kembalian', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('lunas', 'Lunas'), ('batal', 'Dibatalkan')], default='lunas', max_length=10)),
                ('catatan', models.TextField(blank=True)),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('kasir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transaksi',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=200)),
                ('kode_produk', models.CharField(max_length=30)),
                ('harga_satuan', models.DecimalField(decimal_places=0, max_digits=12)),
                ('jumlah', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasir.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kasir.transaksi')),
            ],
        ),
    ]
